apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-app
  labels:
    app: greetings-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greetings-app
  template:
    metadata:
      labels:
        app: greetings-app
    spec:
      containers:
      - name: greetings-app
        image: xlucasdemelo/greetings:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greetings-service
spec:
  selector:
    app: greetings-app
  ports:
    - port: 8888
      targetPort: 8080
      nodePort: 30008
  type: LoadBalancer